[profile.release]
panic = 'unwind'

[workspace]
members = [
	'node',
	'runtime',
	'pallets/*',

	'pallets/cml/runtime-api',
	'pallets/cml/rpc',

	'pallets/machine/rpc',
	'pallets/machine/runtime-api',

	'pallets/genesis-exchange/rpc',
	'pallets/genesis-exchange/runtime-api',
]
