version: "3.2"

services:
  build:
    container_name: tea-camellia-build 
    image: paritytech/ci-linux:production
    working_dir: /tearust/tea-camellia
    ports:
      - "9944:9944"
    environment:
      - CARGO_HOME=/tearust/.cargo
    volumes:
      - ../:/tearust
    command: bash -c "cargo build --release --target-dir /tearust/tea-camellia/docker/target"
