[package]
authors = ['TeaRust']
build = 'build.rs'
description = 'Tea layer1.'
edition = '2018'
homepage = 'https://teaproject.org'
license = 'GPL-3.0'
name = 'tea-camellia'
repository = 'https://github.com/tearust/tea-camellia'
version = '0.0.1'

[[bin]]
name = 'tea-camellia'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[build-dependencies]
substrate-build-script-utils = {version = '3.0.0', git = 'https://github.com/paritytech/substrate.git', rev = '83808aa'}

[dependencies]
log = "0.4.8"
jsonrpc-core = '15.1.0'
structopt = '0.3.8'
hex = '0.4.3'
hex-literal = '0.3.1'
csv = '1.1'

# Substrate dependencies
sc-basic-authorship = {version = '0.9.0', git = 'https://github.com/paritytech/substrate.git', rev = '83808aa'}
sc-cli = {features = ['wasmtime'], version = '0.9.0', git = 'https://github.com/paritytech/substrate.git', rev = '83808aa'}
sc-client-api = {version = '3.0.0', git = 'https://github.com/paritytech/substrate.git', rev = '83808aa'}
sc-consensus = {version = '0.9.0', git = 'https://github.com/paritytech/substrate.git', rev = '83808aa'}
sc-consensus-babe = {version = '0.9.0', git = 'https://github.com/paritytech/substrate.git', rev = '83808aa'}
sc-consensus-uncles = {version = '0.9.0', git = 'https://github.com/paritytech/substrate.git', rev = '83808aa'}
sc-executor = {features = ['wasmtime'], version = '0.9.0', git = 'https://github.com/paritytech/substrate.git', rev = '83808aa'}
sc-finality-grandpa = {version = '0.9.0', git = 'https://github.com/paritytech/substrate.git', rev = '83808aa'}
sc-keystore = {version = '3.0.0', git = 'https://github.com/paritytech/substrate.git', rev = '83808aa'}
sc-rpc = {version = '3.0.0', git = 'https://github.com/paritytech/substrate.git', rev = '83808aa'}
sc-rpc-api = {version = '0.9.0', git = 'https://github.com/paritytech/substrate.git', rev = '83808aa'}
sc-service = {features = ['wasmtime'], version = '0.9.0', git = 'https://github.com/paritytech/substrate.git', rev = '83808aa'}
sc-telemetry = {version = '3.0.0', git = 'https://github.com/paritytech/substrate.git', rev = '83808aa'}
sc-transaction-pool = {version = '3.0.0', git = 'https://github.com/paritytech/substrate.git', rev = '83808aa'}
sc-authority-discovery = {version = '0.9.0', git = 'https://github.com/paritytech/substrate.git', rev = '83808aa'}

sp-api = {version = '3.0.0', git = 'https://github.com/paritytech/substrate.git', rev = '83808aa'}
sp-block-builder = {version = '3.0.0', git = 'https://github.com/paritytech/substrate.git', rev = '83808aa'}
sp-blockchain = {version = '3.0.0', git = 'https://github.com/paritytech/substrate.git', rev = '83808aa'}
sp-consensus = {version = '0.9.0', git = 'https://github.com/paritytech/substrate.git', rev = '83808aa'}
sp-consensus-babe = {version = '0.9.0', git = 'https://github.com/paritytech/substrate.git', rev = '83808aa'}
sp-core = {version = '3.0.0', git = 'https://github.com/paritytech/substrate.git', rev = '83808aa'}
sp-finality-grandpa = {version = '3.0.0', git = 'https://github.com/paritytech/substrate.git', rev = '83808aa'}
sp-inherents = {version = '3.0.0', git = 'https://github.com/paritytech/substrate.git', rev = '83808aa'}
sp-runtime = {version = '3.0.0', git = 'https://github.com/paritytech/substrate.git', rev = '83808aa'}
sp-transaction-pool = {version = '3.0.0', git = 'https://github.com/paritytech/substrate.git', rev = '83808aa'}
sp-timestamp = {version = '3.0.0', git = 'https://github.com/paritytech/substrate.git', rev = '83808aa'}
sp-authorship = {version = '3.0.0', git = 'https://github.com/paritytech/substrate.git', rev = '83808aa'}
sp-authority-discovery = {version = '3.0.0', git = 'https://github.com/paritytech/substrate.git', rev = '83808aa'}

substrate-frame-rpc-system = {version = '3.0.0', git = 'https://github.com/paritytech/substrate.git', rev = '83808aa'}

frame-benchmarking = {version = '3.1.0', git = 'https://github.com/paritytech/substrate.git', rev = '83808aa'}
frame-benchmarking-cli = {version = '3.0.0', git = 'https://github.com/paritytech/substrate.git', rev = '83808aa'}

pallet-im-online = {version = '3.0.0', git = 'https://github.com/paritytech/substrate.git', rev = '83808aa'}
pallet-transaction-payment-rpc = {version = '3.0.0', git = 'https://github.com/paritytech/substrate.git', rev = '83808aa'}
pallet-authority-discovery = {version = '3.0.0', git = 'https://github.com/paritytech/substrate.git', rev = '83808aa'}

# local dependencies
camellia-runtime = {version = '0.0.1', path = '../runtime'}
cml-runtime-api = {path = '../pallets/cml/runtime-api'}
cml-rpc = {path = '../pallets/cml/rpc'}
auction-runtime-api = {default-features = false, path = '../pallets/auction/runtime-api'}
auction-rpc = {path = '../pallets/auction/rpc'}
genesis-bank-runtime-api = {path = '../pallets/genesis-bank/runtime-api'}
genesis-bank-rpc = {path = '../pallets/genesis-bank/rpc'}
genesis-exchange-runtime-api = {path = '../pallets/genesis-exchange/runtime-api'}
genesis-exchange-rpc = {path = '../pallets/genesis-exchange/rpc'}
bonding-curve-runtime-api = {path = '../pallets/bonding-curve/runtime-api'}
bonding-curve-rpc = {path = '../pallets/bonding-curve/rpc'}

[features]
default = []
runtime-benchmarks = ['camellia-runtime/runtime-benchmarks']
fast = ['camellia-runtime/fast']
