name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
        target: x86_64-unknown-linux-gnu, wasm32-unknown-unknown
      run: cargo build --verbose
    - name: Run tests
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
        target: x86_64-unknown-linux-gnu, wasm32-unknown-unknown
      run: cargo test --verbose
