name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build and Test
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
        target: wasm32-unknown-unknown
    - run: cargo build --verbose
    - run: cargo clean
    - run: cargo test --verbose
